<<<<<<< HEAD
# Generated by Django 4.1 on 2022-09-13 13:45
=======
# Generated by Django 4.1 on 2022-09-13 15:02
>>>>>>> 13ce7717ffea9287c2a7016a2915bf1fcc52dab4

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categories_followed',
            field=models.ManyToManyField(related_name='followed_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
