# Generated by Django 4.1 on 2022-09-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='post',
        ),
    ]
