# Generated by Django 4.1 on 2022-09-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="post",
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
