# Generated by Django 4.1 on 2022-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_categories_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
